version: '3'
services:
  laravel:
    build: .
    ports:
      - "4000:80"
      - "8000:8000"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.6.36
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=voltaqui
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
volumes:
  db_data:
